### PR TITLE
Added link to Docker Hub. Added link to page source code.

### PR DESCRIPTION
**Pull request by mkevac**

### CODE REVIEW

**Comment by alexanderilyin** [comment]
@mkevac can you please add `Dockerfile` as well?

**Comment by mkevac** [comment]
@alexanderilyin we are now using pinba2 instead of this one

**Comment by alexanderilyin** [comment]
@mkevac thanks for the update. Is this right place https://github.com/anton-povarov/pinba2 ?

**Comment by mkevac** [comment]
@alexanderilyin yes

**Comment by alexanderilyin** [comment]
@mkevac please close this PR. I don't have permissions to do so.

**Comment by alexanderilyin** [comment]
@mkevac please close this PR. I just want to have my GitHub dashboards clean an tidy. Thanks in advance.

**Pull request closed without merging**
